// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "patients_types.h"
#include <Rcpp.h>

using namespace Rcpp;

// randomMajorCpp
Rcpp::NumericVector randomMajorCpp(int n);
RcppExport SEXP _patients_randomMajorCpp(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(randomMajorCpp(n));
    return rcpp_result_gen;
END_RCPP
}
// icd9RandomShortN
VecStr icd9RandomShortN(VecStr::size_type n);
RcppExport SEXP _patients_icd9RandomShortN(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< VecStr::size_type >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(icd9RandomShortN(n));
    return rcpp_result_gen;
END_RCPP
}
// icd9RandomShortV
VecStr icd9RandomShortV(VecStr::size_type n);
RcppExport SEXP _patients_icd9RandomShortV(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< VecStr::size_type >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(icd9RandomShortV(n));
    return rcpp_result_gen;
END_RCPP
}
// icd9RandomShortE
VecStr icd9RandomShortE(VecStr::size_type n);
RcppExport SEXP _patients_icd9RandomShortE(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< VecStr::size_type >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(icd9RandomShortE(n));
    return rcpp_result_gen;
END_RCPP
}
// icd9RandomShort
CV icd9RandomShort(unsigned int n);
RcppExport SEXP _patients_icd9RandomShort(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(icd9RandomShort(n));
    return rcpp_result_gen;
END_RCPP
}
