# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

randomMajorCpp <- function(n) {
    .Call(`_patients_randomMajorCpp`, n)
}

#' @rdname icd9RandomShort
#' @keywords internal
icd9RandomShortN <- function(n = 5L) {
    .Call(`_patients_icd9RandomShortN`, n)
}

#' @rdname icd9RandomShort
#' @keywords internal
icd9RandomShortV <- function(n = 5L) {
    .Call(`_patients_icd9RandomShortV`, n)
}

#' @rdname icd9RandomShort
#' @keywords internal
icd9RandomShortE <- function(n = 5L) {
    .Call(`_patients_icd9RandomShortE`, n)
}

#' Generate random short-form ICD-9 codes
#'
#' Quick pseudo-random by picking numeric, 'V' or 'E' based on modulo three of
#' the number, with predominance of purely numeric codes.
#' @keywords internal
icd9RandomShort <- function(n = 5L) {
    .Call(`_patients_icd9RandomShort`, n)
}

